run:
	./looking_at_issues_and_fields.py --config ./tap_files/tap_config.json --properties ./tap_files/properties.json --catalog ./tap_files/catalog.json --state ./tap_files/tap_state.json

setup:
	cp /tmp/tap_config.json ./tap_files/tap_config.json
	cp /tmp/properties.json ./tap_files/properties.json
	cp /tmp/catalog.json    ./tap_files/catalog.json
	cp /tmp/tap_state.json  ./tap_files/tap_state.json
